---
title: "reuniao-2"
author: "Guilherme Antonio"
date: "September 4, 2018"
output: html_document
---

# Algoritmo de Metropolis-Hastings.

Temos $X|\theta ~ N(\theta,1)$ e $\theta \sim N(0,1)$.
Queremos calcular propriedades de $f(\theta|X=2)$.
Sabemos que

$$
\begin{align*}
f(\theta|X=2) 
&\propto f(\theta)f(X=2|\theta) \\
&= dnorm(\theta,0,1) * dnorm(2,theta,1)
\end{align*}
$$

```{r, cache = TRUE}
metropolis = function(B = 10^5)
{
  theta = rep(NA, B)
  theta[1] = rnorm(1, 0, 1)
  g = function(theta) dnorm(theta, 0 , 1) * dnorm(2, theta, 1)
  for(ii in 2:B)
  {
    theta_prop = theta[ii-1] + rnorm(1, 0, 1)
    L = g(theta_prop)/g(theta[ii-1])
    theta[ii] = theta_prop
    if(runif(1, 0, 1) > L) theta[ii] = theta[ii-1]
  }
  theta
}

theta = metropolis()
```

```{r}
mean(theta) # estimar E[theta|X = 2]
mean(theta^2) - mean(theta)^2 # estimar V[theta|X = 2]
mean(theta > 2) # estimar P(theta > 2|X = 2)
```

## Problema 1

Temos $\theta \sim \text{Cauchy}$ e
$X|\theta \sim N(0,1)$.
Calcular $E[\theta|X=2]$ e $\V[\theta|X=2]$.

## Problema 2

Temos $\theta \sim \Gamma(1,1)$ e
$X|\theta \sim Exp(\theta)$.
Calcular $E[\theta|X=0.5]$ e $\V[\theta|X=0.5]$.
